name: Tests

on: repository_dispatch

jobs:
  tests:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.action, 'Vercel Build') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: yarn

      - name: Run Mocha Tests
        env:
          BS_NAME: ${{ secrets.BS_NAME }}
          BS_TOKEN: ${{ secrets.BS_TOKEN }}
        run: yarn test
